#playbook.yml
- name: Jitsi Install
  hosts: all
  #vars_files:
  #  - secrets.yml
  become: yes
  gather_facts: yes
  pre_tasks:
    - name: Log who is running the playbook
      debug:
        msg: "Playbook triggered by {{ lookup('env','USER') }}"

    - name: Verify -l-argument is used
      fail:
        msg: "❌ This playbook are not allowed without -l-argument (ex. -l qa eller -l prod)"
      run_once: true
      when: ansible_limit is not defined

  roles:
    - versions_check  # Sets already_installed, nextcloud, postgresql, redis, elastic, npush, drawio, collabora, whiteboard, + _installed_version and _installed yes/no 
    - containers_stop
    - setup_env
    - install_local_images
    - install_repo_images
    - copy_jitsi
    - modify_templates
    - gen_passwords
    - create_network
    - container_not_pods
    - containers_start

    - versions_register
    - post_log
