---
# Use images from repo or local tar files
use_local_tar_images: "true"

# Local image repo, can be left empty for default to jitsi
local_imagee_repo: "jitsi" 

# Jitsi
jitsi_version: "stable-10741"

jitsi_web_name: "web"
jitsi_prosody_name: "prosody"
jitsi_jvb_name: "jvb"
jitsi_jicofo_name: "jicofo"

web_version: "{{ jitsi_version }}"
prosody_version: "{{ jitsi_version }}"
jvb_version: "{{ jitsi_version }}"
jicofo_version: "{{ jitsi_version }}"

jitsi_web_image: "web.tar"
jitsi_prosody_image: "prosody.tar"
jitsi_jvb_image: "jvb.tar"
jitsi_jicofo_image: "jicofo.tar"
