---
- name: Debug already_installed
  ansible.builtin.debug:
    msg: "already_installed = {{ already_installed }}"
    
- name: Stoppar containrar - Jitsi
  command: "{{ container_compose_system }} down"
  args:
    chdir: "{{ remote_working_directory }}/{{ org_name }}/jitsi"
  become_user: "{{ podman_user }}"
  when: already_installed

- name: Stoppar containrar - Nginx
  command: "{{ container_compose_system }} -f docker-compose-{{ item.file }}.yml down"
  args:
    chdir: "{{ remote_working_directory }}/{{ org_name }}"
  loop:
      #- { container: "{{ keycloak_info }}", installed: "{{ keycloak_info }}_installed",  file: "{{ keycloak_info }}" }
      #- { container: "{{ php_info }}",   installed: "{{ php_info }}_installed",  file: "{{ keycloak_info }}" }
    - { container: "{{ nginx_info }}",    installed: "{{ nginx_info }}_installed",  file: "{{ nginx_info }}" }
  loop_control:
    label: "{{ item.container }}"
  become_user: "{{ podman_user }}"
  when: already_installed
