---   
- name: Stops containers
  command: "{{ container_compose_system }} down"
  args:
    chdir: "{{ remote_working_directory }}/{{ org_name }}/jitsi"
  become_user: "{{ podman_user }}"
  when: already_installed

- name: Remove Prosody accounts. DThey will be created at next start up
  ansible.builtin.file:
    path: "{{ remote_working_directory }}/{{ org_name }}/jitsi/prosody/data/auth%2emeet%2ejitsi/accounts/{{ item }}"
    state: absent
  loop:
    - focus.dat
    - jvb.dat
  become_user: "{{ podman_user }}"
