---
- name: Inkluderar förberedelser
  ansible.builtin.include_tasks: prepare.yml

- name: Inkluderar Docker Compose-installation
  ansible.builtin.include_tasks: compose.yml

- name: Inkluderar containerstart
  ansible.builtin.include_tasks: start.yml

- name: Inkluderar Keycloak-konfiguration
  ansible.builtin.include_tasks: keycloak.yml
