---
- name: Not use pods, only conainers
  ansible.builtin.blockinfile:
    path: "{{ remote_working_directory }}/{{ org_name }}/jitsi/docker-compose.yml"
    insertbefore: '^services:'
    marker: ""
    block: |
      x-podman:
        in_pod: false
  become_user: "{{ podman_user }}"
  when: container_system == "podman"